#!/usr/bin/env bash
#
# Bug-bash automatizado: clona 3 repositorios reales (Next.js app, librería TS
# pura, monorepo con JSX), abre cada archivo .js/.ts/.jsx/.tsx contra el
# servidor LSP, y reporta:
#
#   - Archivos que parsean sin errores tree-sitter
#   - Archivos que producen scope-maps no vacíos (oxc semantic ok)
#   - Archivos que producen ERROR/MISSING en el árbol (parser tolerante)
#   - Crashes / timeouts (NUNCA deberían ocurrir)
#
# Uso:
#   scripts/bug-bash.sh                    # corre los 3 repos
#   scripts/bug-bash.sh next-zero          # solo uno
#
# Salida: docs/bug-bash-report.md (sobrescrito en cada corrida).
#
# NOTA: este script verifica robustez (no crashes) automáticamente, pero NO
# inspecciona si el COLOREADO se ve bien — eso requiere ojo humano y queda
# documentado como follow-up en docs/bug-bash-report.md.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

# Allowlist de fixtures. Cada entrada es: nombre, repo URL, revisión, glob.
# Usamos repos pequeños y conocidos, fijados a un tag/sha estable para
# reproducibilidad.
FIXTURES=(
  # Next.js app (de los examples oficiales de Vercel)
  "next-blog|https://github.com/vercel/examples.git|main|solutions/blog/**/*.{ts,tsx}"
  # Librería TS pura
  "zod|https://github.com/colinhacks/zod.git|v3.23.8|src/**/*.ts"
  # Monorepo con JSX (Preact tiene paquetes con JSX/TSX mezclados)
  "preact|https://github.com/preactjs/preact.git|10.24.0|src/**/*.{js,ts,tsx}"
)

ONLY="${1:-}"

WORKDIR="$PROJECT_ROOT/.bug-bash"
REPORT="$PROJECT_ROOT/docs/bug-bash-report.md"
BIN="$PROJECT_ROOT/target/release/js-sem-highlight"

if [[ ! -x "$BIN" ]]; then
  echo "==> Binary not found at $BIN. Building..."
  cargo build --release --bin js-sem-highlight
fi

mkdir -p "$WORKDIR" "$(dirname "$REPORT")"

cat > "$REPORT" <<'HEADER'
# Bug-bash report

Automated robustness check. Generated by `scripts/bug-bash.sh`.

For each fixture we open every matching file against the LSP server, count
clean parses vs. recoverable errors vs. crashes, and report.

**This script does NOT judge the visual quality of highlighting.** That is a
human task. Items flagged as TODO at the bottom of this report require
manual inspection before tagging v1.0.

HEADER

# ----------------------------------------------------------------------------
# Tiny LSP client: writes one initialize + N didOpen + shutdown to the server,
# parses responses, and counts parse errors per file.
# ----------------------------------------------------------------------------

probe_repo() {
  local name="$1"
  local repo_url="$2"
  local rev="$3"
  local glob="$4"
  local repo_dir="$WORKDIR/$name"

  if [[ ! -d "$repo_dir" ]]; then
    echo "==> Cloning $name from $repo_url@$rev"
    git clone --quiet --depth 50 --branch "$rev" "$repo_url" "$repo_dir" \
      || git clone --quiet "$repo_url" "$repo_dir"
    if ! git -C "$repo_dir" rev-parse --verify "$rev" >/dev/null 2>&1; then
      echo "    (revision $rev not found, using HEAD)"
    else
      git -C "$repo_dir" checkout --quiet "$rev"
    fi
  fi

  echo "==> Probing $name"
  # Glob expansion via bash; protected by `set -f` to avoid surprise expansion
  # of patterns we don't control (none here, but defense-in-depth).
  set -f
  IFS='/' read -ra parts <<< "$glob"
  set +f

  # Use Python for robust glob + LSP framing. Python ships with macOS/Linux.
  python3 "$PROJECT_ROOT/scripts/bug-bash-probe.py" \
    --bin "$BIN" \
    --root "$repo_dir" \
    --glob "$glob" \
    --name "$name" \
    >> "$REPORT"
}

for entry in "${FIXTURES[@]}"; do
  IFS='|' read -r name url rev glob <<< "$entry"
  if [[ -n "$ONLY" && "$ONLY" != "$name" ]]; then
    continue
  fi
  probe_repo "$name" "$url" "$rev" "$glob"
done

cat >> "$REPORT" <<'FOOTER'

## Manual follow-up

- [ ] Open one Next.js app fixture in VS Code with the .vsix installed and
      verify visually that JSX intrinsics vs. components are colored differently.
- [ ] Open the zod fixture and verify type-only imports are dimmed correctly.
- [ ] Open a Preact .tsx and verify generic-vs-JSX disambiguation does not
      break the tokens around `<T,>(x: T) => x`.
FOOTER

echo
echo "==> Report written to $REPORT"
